### ISSUE TITLE
Release number versioning doesn't conform to RubyGems semantic versioning

### ISSUE THREAD

**Issue by zinga666** [mvz/gir_ffi-gnome_keyring#5]
Hi,

a `gem install gir_ffi-gnome_keyring -v "~>0.0.3"` on a Linux machine with `Ruby 2.3.8` fails because this gets resolved to the latest `0.0.11` version which in turn requires `gir_ffi` version `~> 0.15.1` which requires `Ruby >= 2.5`.

While it is clear to me that `Ruby 2.3.8` is EOL and that the `gir_ffi` Gem (and extension Gems like this one) will move on and drop support of old (unsupported) Ruby versions I think that the versioning scheme used with this Gem here is not conforming to the [RubyGems Semantic Versioning](https://guides.rubygems.org/patterns/#semantic-versioning) policy, i.e. when the Gem breaks backwards compatibility it should not only increase the patch level but at least the minor level.

So, dropping support for a Ruby version should imho not be done within the same minor version. Also, a new version of the `gir_ffi` Gem should also result in a (at least) new minor version, I guess (i.e. the extension Gem(s) should follow the versioning in the base Gem).

**Comment by mvz** [comment]
Hi @zinga666, I don't agree for two reasons:

- Part of the semantic versioning rule is that all bets are off for pre-1.0 versions. In the `gir_ffi` family of gems, I generally strive for general compatibility between minor versions after 0.1.0, but this gem is still in the 0.0.x phase, so again, all bets are off. See https://semver.org/#spec-item-4
- Ruby is a dependency of this gem, and any update of dependencies is *not* grounds for a major version increase according to SemVer. See https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api. I realise rubygems has a hard time taking the required ruby version into account, but I consider that a bug in rubygems.
